[SERVICE]
    Parsers_File /home/codespace/fluent-bit-plugin/parsers.conf
    Flush        1
    Log_Level    info

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/logs.txt
    Tag             mylogs
    Parser          custom_parser
    Read_from_Head  true
    Path_Key        source_file

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/json_logs.txt
    Tag             jsonlogs
    Parser          json_parser
    Read_from_Head  true
    Path_Key        source_file

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/*.log
    Tag             stratidlogs
    Parser          custom_parser
    Read_from_Head  true
    Path_Key        source_file

[FILTER]
    Name   grep
    Match  *
    Regex  level (INFO|WARNING|ERROR|CRITICAL)

[FILTER]
    Name           extract_id
    Match          stratidlogs
    filename_key   source_file
    file_pattern _([0-9]+)_
    target_key     strat_id

[FILTER]
    Name         count_filter
    Match_Regex  ^(mylogs|jsonlogs|stratidlogs)$
    output_key   count

[FILTER]
    Name          rewrite_tag
    Match_Regex   ^(mylogs|jsonlogs|stratidlogs)$
    Rule          $message  %%[^%]+%%  special_alert  false
    Emitter_Name  special_alert_emitter

[OUTPUT]
    Name              batch_http
    Match_Regex       ^(mylogs|jsonlogs|stratidlogs)$
    host              127.0.0.1
    port              8080
    path              /portfolio_log_analyzer/query-handle_portfolio_alerts
    batch_size        200
    batch_timeout_sec 2
    collapse_alerts   true
    retry_limit       3
    retry_delay_sec   1


[OUTPUT]
    Name              batch_http
    Match             special_alert
    host              127.0.0.1
    port              8081
    path              /portfolio_log_analyzer/query-handle_special_alerts
    batch_size        200
    batch_timeout_sec 2
    collapse_alerts   true
    retry_limit       3
    retry_delay_sec   1
