[SERVICE]
    Parsers_File /home/codespace/fluent-bit-plugin/parsers.conf
    Flush        1
    Log_Level    info

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/logs.txt
    Tag             mylogs
    Parser          custom_parser
    Read_from_Head  true
    Path_Key        source_file

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/json_logs.txt
    Tag             jsonlogs
    Parser          json_parser
    Read_from_Head  true
    Path_Key        source_file

[INPUT]
    Name            tail
    Path            /home/codespace/fluent-bit-plugin/*.log
    Tag             stratidlogs
    Parser          custom_parser
    Read_from_Head  true
    Path_Key        source_file

[FILTER]
    Name   grep
    Match  *
    Regex  level (INFO|WARNING|ERROR|CRITICAL)

[FILTER]
    Name           extract_id
    Match          stratidlogs
    filename_key   source_file
    file_pattern _([0-9]+)_
    target_key     strat_id

[FILTER]
    Name         count_filter
    Match_Regex  ^(mylogs|jsonlogs|stratidlogs)$
    output_key   count

[FILTER]
    Name          rewrite_tag
    Match_Regex   ^(mylogs|jsonlogs|stratidlogs)$
    Rule          $message  %%[^%]+%%  special_alert  false
    Emitter_Name  special_alert_emitter

[OUTPUT]
    Name        stdout
    Match_Regex ^(mylogs|jsonlogs|stratidlogs)$
    Format      json_lines

[OUTPUT]
    Name   stdout
    Match  special_alert
    Format json_lines
